[[plugins]]
id = "app-search"
name = "Search"
kind = "app"

[[plugins]]
id = "media-provider-filesystem"
name = "Filesystem"
kind = "media-provider"

[[plugins]]
id = "transcriber-whisper"
name = "Whisper CPU"
kind = "transcriber"
