[[plugins]]
id = "app-search"
name = "Search"
kind = "App"

[[plugins]]
id = "media-provider-filesystem"
name = "Filesystem"
kind = "MediaProvider"

[[plugins]]
id = "transcriber-whisper"
name = "Whisper CPU"
kind = "Transcriber"
